name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Archive Code
        uses: actions/upload-artifact@v3
        with:
          name: BrainAttackGame-Files
          path: .
