name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Zip Artifact
        run: |
          zip -r BrainAttackGame.zip . -x "*.git*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BrainAttackGame-Files
          path: BrainAttackGame.zip
